DEFAULT_TASKS = ("ag_news", "yelp_review_full", "dbpedia_14")
DEFAULT_TRAIN_SAMPLES = 1000
DEFAULT_EVAL_SAMPLES = 100
DEFAULT_CONTINUAL_EPOCHS = 5
DEFAULT_LORA_TRAIN_SAMPLES = 2000
DEFAULT_LORA_EVAL_SAMPLES = 200
DEFAULT_LORA_CONTINUAL_EPOCHS = 10
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_ORTHOGONAL_PENALTY_WEIGHT = 0.5
DEFAULT_L2_PENALTY_WEIGHT = 0.0
STACK_ADAPTER_NAME = "stack"

DEFAULT_CONTINUAL_OUTPUT_DIR = "artifacts/dynamic_lora/ag_news_yelp_dbpedia"
DEFAULT_CONTINUAL_FULL_OUTPUT_DIR = "artifacts/dynamic_lora/ag_news_yelp_dbpedia_full_finetune"
DEFAULT_UNLEARN_OUTPUT_DIR = "artifacts/dynamic_lora/unlearn"
DEFAULT_STACKED_ADAPTER_DIR = f"{DEFAULT_CONTINUAL_OUTPUT_DIR}/final/{STACK_ADAPTER_NAME}"
