DEFAULT_TASKS = ("ag_news", "yelp_review_full", "dbpedia_14")
DEFAULT_TRAIN_SAMPLES = 2000
DEFAULT_EVAL_SAMPLES = 500
DEFAULT_CONTINUAL_EPOCHS = 20
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_ORTHOGONAL_PENALTY_WEIGHT = 0.5
DEFAULT_L2_PENALTY_WEIGHT = 0.0
STACK_ADAPTER_NAME = "stack"

DEFAULT_CONTINUAL_OUTPUT_DIR = "artifacts/dynamic_lora/ag_news_yelp_dbpedia"
DEFAULT_UNLEARN_OUTPUT_DIR = "artifacts/dynamic_lora/unlearn"
DEFAULT_STACKED_ADAPTER_DIR = f"{DEFAULT_CONTINUAL_OUTPUT_DIR}/final/{STACK_ADAPTER_NAME}"
